FROM mcr.microsoft.com/dotnet/monitor

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
#RUN addgroup --gid 1000 appuser && adduser -u 1000 -gid 1000 --disabled-password --gecos "" appuser && chown -R appuser /app
RUN adduser -u 1000 --disabled-password --gecos "" appuser
USER 1000
